/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_opennfc_MethodAutogen */

#ifndef _Included_org_opennfc_MethodAutogen
#define _Included_org_opennfc_MethodAutogen
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    W14Part3ExchangeData
 * Signature: (IIII[I)V
 */
JNIEXPORT void JNICALL Java_org_opennfc_MethodAutogen_W14Part3ExchangeData
  (JNIEnv *, jclass, jint, jint, jint, jint, jintArray);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    W14Part3GetConnectionInfoBuffer
 * Signature: (I[B)I
 */
JNIEXPORT jint JNICALL Java_org_opennfc_MethodAutogen_W14Part3GetConnectionInfoBuffer
  (JNIEnv *, jclass, jint, jbyteArray);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    W14Part3ListenToCardDetectionTypeB
 * Signature: (IIIZII[B[I)I
 */
JNIEXPORT jint JNICALL Java_org_opennfc_MethodAutogen_W14Part3ListenToCardDetectionTypeB
  (JNIEnv *, jclass, jint, jint, jint, jboolean, jint, jint, jbyteArray, jintArray);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    W14Part3SetTimeout
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_opennfc_MethodAutogen_W14Part3SetTimeout
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    W14Part4ExchangeData
 * Signature: (IIII[I)V
 */
JNIEXPORT void JNICALL Java_org_opennfc_MethodAutogen_W14Part4ExchangeData
  (JNIEnv *, jclass, jint, jint, jint, jint, jintArray);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    W14Part4GetConnectionInfoBuffer
 * Signature: (I[B)I
 */
JNIEXPORT jint JNICALL Java_org_opennfc_MethodAutogen_W14Part4GetConnectionInfoBuffer
  (JNIEnv *, jclass, jint, jbyteArray);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    W14Part4ListenToCardDetectionTypeA
 * Signature: (IIZII[I)I
 */
JNIEXPORT jint JNICALL Java_org_opennfc_MethodAutogen_W14Part4ListenToCardDetectionTypeA
  (JNIEnv *, jclass, jint, jint, jboolean, jint, jint, jintArray);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    W14Part4ListenToCardDetectionTypeB
 * Signature: (IIIZII[B[I)I
 */
JNIEXPORT jint JNICALL Java_org_opennfc_MethodAutogen_W14Part4ListenToCardDetectionTypeB
  (JNIEnv *, jclass, jint, jint, jint, jboolean, jint, jint, jbyteArray, jintArray);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    W14Part4SetNAD
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_opennfc_MethodAutogen_W14Part4SetNAD
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    W15GetConnectionInfoBuffer
 * Signature: (I[B)I
 */
JNIEXPORT jint JNICALL Java_org_opennfc_MethodAutogen_W15GetConnectionInfoBuffer
  (JNIEnv *, jclass, jint, jbyteArray);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    W15IsWritable
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_opennfc_MethodAutogen_W15IsWritable
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    W15ListenToCardDetection
 * Signature: (III[I)I
 */
JNIEXPORT jint JNICALL Java_org_opennfc_MethodAutogen_W15ListenToCardDetection
  (JNIEnv *, jclass, jint, jint, jint, jintArray);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    W15Read
 * Signature: (IIII[I)V
 */
JNIEXPORT void JNICALL Java_org_opennfc_MethodAutogen_W15Read
  (JNIEnv *, jclass, jint, jint, jint, jint, jintArray);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    W15SetAttribute
 * Signature: (IIIII[I)V
 */
JNIEXPORT void JNICALL Java_org_opennfc_MethodAutogen_W15SetAttribute
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jintArray);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    W15SetTagSize
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_org_opennfc_MethodAutogen_W15SetTagSize
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    W15Write
 * Signature: (IIIIZ[I)V
 */
JNIEXPORT void JNICALL Java_org_opennfc_MethodAutogen_W15Write
  (JNIEnv *, jclass, jint, jint, jint, jint, jboolean, jintArray);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    W7816CloseLogicalChannel
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_opennfc_MethodAutogen_W7816CloseLogicalChannel
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    W7816ExchangeAPDU
 * Signature: (IIII[I)V
 */
JNIEXPORT void JNICALL Java_org_opennfc_MethodAutogen_W7816ExchangeAPDU
  (JNIEnv *, jclass, jint, jint, jint, jint, jintArray);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    W7816GetATR
 * Signature: (I[B[I)I
 */
JNIEXPORT jint JNICALL Java_org_opennfc_MethodAutogen_W7816GetATR
  (JNIEnv *, jclass, jint, jbyteArray, jintArray);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    W7816GetATRSize
 * Signature: (I[I)I
 */
JNIEXPORT jint JNICALL Java_org_opennfc_MethodAutogen_W7816GetATRSize
  (JNIEnv *, jclass, jint, jintArray);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    W7816GetResponseAPDUData
 * Signature: (I[B[I)I
 */
JNIEXPORT jint JNICALL Java_org_opennfc_MethodAutogen_W7816GetResponseAPDUData
  (JNIEnv *, jclass, jint, jbyteArray, jintArray);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    W7816OpenLogicalChannel
 * Signature: (III[I)V
 */
JNIEXPORT void JNICALL Java_org_opennfc_MethodAutogen_W7816OpenLogicalChannel
  (JNIEnv *, jclass, jint, jint, jint, jintArray);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WBasicCancelOperation
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_opennfc_MethodAutogen_WBasicCancelOperation
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WBasicCheckConnectionProperty
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_opennfc_MethodAutogen_WBasicCheckConnectionProperty
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WBasicCloseHandle
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_opennfc_MethodAutogen_WBasicCloseHandle
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WBasicCloseHandleSafe
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_opennfc_MethodAutogen_WBasicCloseHandleSafe
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WBasicGetConnectionProperties
 * Signature: (I[B)I
 */
JNIEXPORT jint JNICALL Java_org_opennfc_MethodAutogen_WBasicGetConnectionProperties
  (JNIEnv *, jclass, jint, jbyteArray);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WBasicGetConnectionPropertyNumber
 * Signature: (I[I)I
 */
JNIEXPORT jint JNICALL Java_org_opennfc_MethodAutogen_WBasicGetConnectionPropertyNumber
  (JNIEnv *, jclass, jint, jintArray);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WBasicInit
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_opennfc_MethodAutogen_WBasicInit
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WBasicPumpEvent
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_org_opennfc_MethodAutogen_WBasicPumpEvent
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WBasicStopEventLoop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_opennfc_MethodAutogen_WBasicStopEventLoop
  (JNIEnv *, jclass);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WBasicTerminate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_opennfc_MethodAutogen_WBasicTerminate
  (JNIEnv *, jclass);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WBPrimeExchangeData
 * Signature: (IIII[I)V
 */
JNIEXPORT void JNICALL Java_org_opennfc_MethodAutogen_WBPrimeExchangeData
  (JNIEnv *, jclass, jint, jint, jint, jint, jintArray);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WBPrimeGetConnectionInfoBuffer
 * Signature: (I[B)I
 */
JNIEXPORT jint JNICALL Java_org_opennfc_MethodAutogen_WBPrimeGetConnectionInfoBuffer
  (JNIEnv *, jclass, jint, jbyteArray);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WBPrimeListenToCardDetection
 * Signature: (II[B[I)I
 */
JNIEXPORT jint JNICALL Java_org_opennfc_MethodAutogen_WBPrimeListenToCardDetection
  (JNIEnv *, jclass, jint, jint, jbyteArray, jintArray);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WBPrimeSetTimeout
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_opennfc_MethodAutogen_WBPrimeSetTimeout
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WDFCPumpJNICallback
 * Signature: ([I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_opennfc_MethodAutogen_WDFCPumpJNICallback
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WEmulClose
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_opennfc_MethodAutogen_WEmulClose
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WEmulGetMessageData
 * Signature: (I[B[I)I
 */
JNIEXPORT jint JNICALL Java_org_opennfc_MethodAutogen_WEmulGetMessageData
  (JNIEnv *, jclass, jint, jbyteArray, jintArray);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WEmulIsPropertySupported
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_opennfc_MethodAutogen_WEmulIsPropertySupported
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WEmulOpenConnectionBuffer
 * Signature: (IIII[BI[I)V
 */
JNIEXPORT void JNICALL Java_org_opennfc_MethodAutogen_WEmulOpenConnectionBuffer
  (JNIEnv *, jclass, jint, jint, jint, jint, jbyteArray, jint, jintArray);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WEmulSendAnswer
 * Signature: (I[B)I
 */
JNIEXPORT jint JNICALL Java_org_opennfc_MethodAutogen_WEmulSendAnswer
  (JNIEnv *, jclass, jint, jbyteArray);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WFeliCaGetConnectionInfoBuffer
 * Signature: (I[B)I
 */
JNIEXPORT jint JNICALL Java_org_opennfc_MethodAutogen_WFeliCaGetConnectionInfoBuffer
  (JNIEnv *, jclass, jint, jbyteArray);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WFeliCaReadSimple
 * Signature: (III[I[B)V
 */
JNIEXPORT void JNICALL Java_org_opennfc_MethodAutogen_WFeliCaReadSimple
  (JNIEnv *, jclass, jint, jint, jint, jintArray, jbyteArray);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WFeliCaWriteSimple
 * Signature: (III[I[B)V
 */
JNIEXPORT void JNICALL Java_org_opennfc_MethodAutogen_WFeliCaWriteSimple
  (JNIEnv *, jclass, jint, jint, jint, jintArray, jbyteArray);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WJavaCreateByteBuffer
 * Signature: ([BII)I
 */
JNIEXPORT jint JNICALL Java_org_opennfc_MethodAutogen_WJavaCreateByteBuffer
  (JNIEnv *, jclass, jbyteArray, jint, jint);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WJavaNDEFWriteMessage
 * Signature: (IIII[I)V
 */
JNIEXPORT void JNICALL Java_org_opennfc_MethodAutogen_WJavaNDEFWriteMessage
  (JNIEnv *, jclass, jint, jint, jint, jint, jintArray);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WJavaNDEFWriteMessageOnAnyTag
 * Signature: (IIII[I)V
 */
JNIEXPORT void JNICALL Java_org_opennfc_MethodAutogen_WJavaNDEFWriteMessageOnAnyTag
  (JNIEnv *, jclass, jint, jint, jint, jint, jintArray);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WJavaNFCControllerGetBooleanProperty
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_opennfc_MethodAutogen_WJavaNFCControllerGetBooleanProperty
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WJavaP2PGetConfigurationBuffer
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_org_opennfc_MethodAutogen_WJavaP2PGetConfigurationBuffer
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WJavaP2PGetLinkPropertiesBuffer
 * Signature: (I[B)I
 */
JNIEXPORT jint JNICALL Java_org_opennfc_MethodAutogen_WJavaP2PGetLinkPropertiesBuffer
  (JNIEnv *, jclass, jint, jbyteArray);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WJavaP2PSetConfigurationBuffer
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_org_opennfc_MethodAutogen_WJavaP2PSetConfigurationBuffer
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WJavaReleaseByteBuffer
 * Signature: (I[B)V
 */
JNIEXPORT void JNICALL Java_org_opennfc_MethodAutogen_WJavaReleaseByteBuffer
  (JNIEnv *, jclass, jint, jbyteArray);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WMifareGetConnectionInfoBuffer
 * Signature: (I[B)I
 */
JNIEXPORT jint JNICALL Java_org_opennfc_MethodAutogen_WMifareGetConnectionInfoBuffer
  (JNIEnv *, jclass, jint, jbyteArray);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WMifareRead
 * Signature: (IIII[I)V
 */
JNIEXPORT void JNICALL Java_org_opennfc_MethodAutogen_WMifareRead
  (JNIEnv *, jclass, jint, jint, jint, jint, jintArray);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WMifareULCAuthenticate
 * Signature: (II[B)V
 */
JNIEXPORT void JNICALL Java_org_opennfc_MethodAutogen_WMifareULCAuthenticate
  (JNIEnv *, jclass, jint, jint, jbyteArray);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WMifareULCSetAccessRights
 * Signature: (II[BIIZ)V
 */
JNIEXPORT void JNICALL Java_org_opennfc_MethodAutogen_WMifareULCSetAccessRights
  (JNIEnv *, jclass, jint, jint, jbyteArray, jint, jint, jboolean);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WMifareULForceULC
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_opennfc_MethodAutogen_WMifareULForceULC
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WMifareULFreezeDataLockConfiguration
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_opennfc_MethodAutogen_WMifareULFreezeDataLockConfiguration
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WMifareULGetAccessRights
 * Signature: (III[I)I
 */
JNIEXPORT jint JNICALL Java_org_opennfc_MethodAutogen_WMifareULGetAccessRights
  (JNIEnv *, jclass, jint, jint, jint, jintArray);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WMifareULRetrieveAccessRights
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_opennfc_MethodAutogen_WMifareULRetrieveAccessRights
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WMifareWrite
 * Signature: (IIIIZ[I)V
 */
JNIEXPORT void JNICALL Java_org_opennfc_MethodAutogen_WMifareWrite
  (JNIEnv *, jclass, jint, jint, jint, jint, jboolean, jintArray);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WMyDGetConnectionInfoBuffer
 * Signature: (I[B)I
 */
JNIEXPORT jint JNICALL Java_org_opennfc_MethodAutogen_WMyDGetConnectionInfoBuffer
  (JNIEnv *, jclass, jint, jbyteArray);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WMyDMoveAuthenticate
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_opennfc_MethodAutogen_WMyDMoveAuthenticate
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WMyDMoveFreezeDataLockConfiguration
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_opennfc_MethodAutogen_WMyDMoveFreezeDataLockConfiguration
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WMyDMoveGetConfiguration
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_opennfc_MethodAutogen_WMyDMoveGetConfiguration
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WMyDMoveSetConfiguration
 * Signature: (IIIIIZ)V
 */
JNIEXPORT void JNICALL Java_org_opennfc_MethodAutogen_WMyDMoveSetConfiguration
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jboolean);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WMyDRead
 * Signature: (IIII[I)V
 */
JNIEXPORT void JNICALL Java_org_opennfc_MethodAutogen_WMyDRead
  (JNIEnv *, jclass, jint, jint, jint, jint, jintArray);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WMyDWrite
 * Signature: (IIIIZ[I)V
 */
JNIEXPORT void JNICALL Java_org_opennfc_MethodAutogen_WMyDWrite
  (JNIEnv *, jclass, jint, jint, jint, jint, jboolean, jintArray);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WNDEFGetTagInfoBuffer
 * Signature: (I[B)I
 */
JNIEXPORT jint JNICALL Java_org_opennfc_MethodAutogen_WNDEFGetTagInfoBuffer
  (JNIEnv *, jclass, jint, jbyteArray);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WNDEFReadMessage
 * Signature: (IIILjava/lang/String;[I)V
 */
JNIEXPORT void JNICALL Java_org_opennfc_MethodAutogen_WNDEFReadMessage
  (JNIEnv *, jclass, jint, jint, jint, jstring, jintArray);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WNDEFReadMessageOnAnyTag
 * Signature: (IIILjava/lang/String;[I)V
 */
JNIEXPORT void JNICALL Java_org_opennfc_MethodAutogen_WNDEFReadMessageOnAnyTag
  (JNIEnv *, jclass, jint, jint, jint, jstring, jintArray);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WNFCControllerFirmwareUpdate
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_opennfc_MethodAutogen_WNFCControllerFirmwareUpdate
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WNFCControllerFirmwareUpdateState
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_opennfc_MethodAutogen_WNFCControllerFirmwareUpdateState
  (JNIEnv *, jclass);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WNFCControllerGetFirmwareProperty
 * Signature: ([BI[C[I)I
 */
JNIEXPORT jint JNICALL Java_org_opennfc_MethodAutogen_WNFCControllerGetFirmwareProperty
  (JNIEnv *, jclass, jbyteArray, jint, jcharArray, jintArray);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WNFCControllerGetMode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_opennfc_MethodAutogen_WNFCControllerGetMode
  (JNIEnv *, jclass);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WNFCControllerGetProperty
 * Signature: (I[C[I)I
 */
JNIEXPORT jint JNICALL Java_org_opennfc_MethodAutogen_WNFCControllerGetProperty
  (JNIEnv *, jclass, jint, jcharArray, jintArray);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WNFCControllerGetRFActivity
 * Signature: ([I[I[I)V
 */
JNIEXPORT void JNICALL Java_org_opennfc_MethodAutogen_WNFCControllerGetRFActivity
  (JNIEnv *, jclass, jintArray, jintArray, jintArray);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WNFCControllerGetRFLock
 * Signature: (I[I[I)V
 */
JNIEXPORT void JNICALL Java_org_opennfc_MethodAutogen_WNFCControllerGetRFLock
  (JNIEnv *, jclass, jint, jintArray, jintArray);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WNFCControllerMonitorException
 * Signature: (I[I)I
 */
JNIEXPORT jint JNICALL Java_org_opennfc_MethodAutogen_WNFCControllerMonitorException
  (JNIEnv *, jclass, jint, jintArray);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WNFCControllerProductionTest
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_opennfc_MethodAutogen_WNFCControllerProductionTest
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WNFCControllerReset
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_opennfc_MethodAutogen_WNFCControllerReset
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WNFCControllerSelfTest
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_opennfc_MethodAutogen_WNFCControllerSelfTest
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WNFCControllerSetRFLock
 * Signature: (IZZI)V
 */
JNIEXPORT void JNICALL Java_org_opennfc_MethodAutogen_WNFCControllerSetRFLock
  (JNIEnv *, jclass, jint, jboolean, jboolean, jint);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WNFCControllerSwitchStandbyMode
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_org_opennfc_MethodAutogen_WNFCControllerSwitchStandbyMode
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WP2PConnect
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_opennfc_MethodAutogen_WP2PConnect
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WP2PCreateSocket
 * Signature: (ILjava/lang/String;I[I)I
 */
JNIEXPORT jint JNICALL Java_org_opennfc_MethodAutogen_WP2PCreateSocket
  (JNIEnv *, jclass, jint, jstring, jint, jintArray);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WP2PEstablishLink
 * Signature: (II[I)V
 */
JNIEXPORT void JNICALL Java_org_opennfc_MethodAutogen_WP2PEstablishLink
  (JNIEnv *, jclass, jint, jint, jintArray);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WP2PGetSocketParameter
 * Signature: (II[I)I
 */
JNIEXPORT jint JNICALL Java_org_opennfc_MethodAutogen_WP2PGetSocketParameter
  (JNIEnv *, jclass, jint, jint, jintArray);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WP2PRead
 * Signature: (III[I)V
 */
JNIEXPORT void JNICALL Java_org_opennfc_MethodAutogen_WP2PRead
  (JNIEnv *, jclass, jint, jint, jint, jintArray);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WP2PRecvFrom
 * Signature: (III[I)V
 */
JNIEXPORT void JNICALL Java_org_opennfc_MethodAutogen_WP2PRecvFrom
  (JNIEnv *, jclass, jint, jint, jint, jintArray);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WP2PSendTo
 * Signature: (IIII[I)V
 */
JNIEXPORT void JNICALL Java_org_opennfc_MethodAutogen_WP2PSendTo
  (JNIEnv *, jclass, jint, jint, jint, jint, jintArray);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WP2PSetSocketParameter
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_org_opennfc_MethodAutogen_WP2PSetSocketParameter
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WP2PShutdown
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_opennfc_MethodAutogen_WP2PShutdown
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WP2PURILookup
 * Signature: (IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_opennfc_MethodAutogen_WP2PURILookup
  (JNIEnv *, jclass, jint, jint, jstring);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WP2PWrite
 * Signature: (III[I)V
 */
JNIEXPORT void JNICALL Java_org_opennfc_MethodAutogen_WP2PWrite
  (JNIEnv *, jclass, jint, jint, jint, jintArray);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WPicoGetConnectionInfoBuffer
 * Signature: (I[B)I
 */
JNIEXPORT jint JNICALL Java_org_opennfc_MethodAutogen_WPicoGetConnectionInfoBuffer
  (JNIEnv *, jclass, jint, jbyteArray);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WPicoIsWritable
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_opennfc_MethodAutogen_WPicoIsWritable
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WPicoRead
 * Signature: (IIII[I)V
 */
JNIEXPORT void JNICALL Java_org_opennfc_MethodAutogen_WPicoRead
  (JNIEnv *, jclass, jint, jint, jint, jint, jintArray);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WPicoWrite
 * Signature: (IIIIZ[I)V
 */
JNIEXPORT void JNICALL Java_org_opennfc_MethodAutogen_WPicoWrite
  (JNIEnv *, jclass, jint, jint, jint, jint, jboolean, jintArray);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WReaderErrorEventRegister
 * Signature: (IIZ[I)I
 */
JNIEXPORT jint JNICALL Java_org_opennfc_MethodAutogen_WReaderErrorEventRegister
  (JNIEnv *, jclass, jint, jint, jboolean, jintArray);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WReaderGetPulsePeriod
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_org_opennfc_MethodAutogen_WReaderGetPulsePeriod
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WReaderHandlerWorkPerformed
 * Signature: (IZZ)V
 */
JNIEXPORT void JNICALL Java_org_opennfc_MethodAutogen_WReaderHandlerWorkPerformed
  (JNIEnv *, jclass, jint, jboolean, jboolean);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WReaderIsPropertySupported
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_opennfc_MethodAutogen_WReaderIsPropertySupported
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WReaderListenToCardDetection
 * Signature: (II[B[I)I
 */
JNIEXPORT jint JNICALL Java_org_opennfc_MethodAutogen_WReaderListenToCardDetection
  (JNIEnv *, jclass, jint, jint, jbyteArray, jintArray);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WReaderPreviousApplicationMatch
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_opennfc_MethodAutogen_WReaderPreviousApplicationMatch
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WReaderSetPulsePeriod
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_opennfc_MethodAutogen_WReaderSetPulsePeriod
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WSecurityAuthenticate
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_org_opennfc_MethodAutogen_WSecurityAuthenticate
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WType1ChipGetConnectionInfoBuffer
 * Signature: (I[B)I
 */
JNIEXPORT jint JNICALL Java_org_opennfc_MethodAutogen_WType1ChipGetConnectionInfoBuffer
  (JNIEnv *, jclass, jint, jbyteArray);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WType1ChipIsWritable
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_opennfc_MethodAutogen_WType1ChipIsWritable
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WType1ChipRead
 * Signature: (IIII[I)V
 */
JNIEXPORT void JNICALL Java_org_opennfc_MethodAutogen_WType1ChipRead
  (JNIEnv *, jclass, jint, jint, jint, jint, jintArray);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WType1ChipWrite
 * Signature: (IIIIZ[I)V
 */
JNIEXPORT void JNICALL Java_org_opennfc_MethodAutogen_WType1ChipWrite
  (JNIEnv *, jclass, jint, jint, jint, jint, jboolean, jintArray);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WVirtualTagCreate
 * Signature: (I[BI[I)I
 */
JNIEXPORT jint JNICALL Java_org_opennfc_MethodAutogen_WVirtualTagCreate
  (JNIEnv *, jclass, jint, jbyteArray, jint, jintArray);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WVirtualTagStart
 * Signature: (IIIZ)V
 */
JNIEXPORT void JNICALL Java_org_opennfc_MethodAutogen_WVirtualTagStart
  (JNIEnv *, jclass, jint, jint, jint, jboolean);

/*
 * Class:     org_opennfc_MethodAutogen
 * Method:    WVirtualTagStop
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_opennfc_MethodAutogen_WVirtualTagStop
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_opennfc_nfctag_MethodAutogen */

#ifndef _Included_org_opennfc_nfctag_MethodAutogen
#define _Included_org_opennfc_nfctag_MethodAutogen
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_opennfc_nfctag_MethodAutogen
 * Method:    WBasicCloseHandle
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_opennfc_nfctag_MethodAutogen_WBasicCloseHandle
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_opennfc_nfctag_MethodAutogen
 * Method:    WJavaNDEFGetMessageContent
 * Signature: (I[B)I
 */
JNIEXPORT jint JNICALL Java_org_opennfc_nfctag_MethodAutogen_WJavaNDEFGetMessageContent
  (JNIEnv *, jclass, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
